# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linear_classification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blinear_classification.proto\x12\x19\x66\x61st_ml_linear_regression\"\xb9\x01\n\x0fTrainingRequest\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\x12N\n\nparameters\x18\x03 \x03(\x0b\x32:.fast_ml_linear_regression.TrainingRequest.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\")\n\x10TrainingResponse\x12\x15\n\rconfiguration\x18\x01 \x01(\t\"8\n\x11PredictionRequest\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\"%\n\x12PredictionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe7\x01\n\x1bLinearClassificationService\x12`\n\x05Train\x12*.fast_ml_linear_regression.TrainingRequest\x1a+.fast_ml_linear_regression.TrainingResponse\x12\x66\n\x07Predict\x12,.fast_ml_linear_regression.PredictionRequest\x1a-.fast_ml_linear_regression.PredictionResponseB\x87\x01\n\x1e\x63om.fastmllinearclassificationB\x1f\x46\x61stMLLinearClassificationProtoP\x01Z\x1d\x66\x61stmllinearclassificationspb\xaa\x02\"Fast.ML.Linear.Classification.Grpcb\x06proto3')



_TRAININGREQUEST = DESCRIPTOR.message_types_by_name['TrainingRequest']
_TRAININGREQUEST_PARAMETERSENTRY = _TRAININGREQUEST.nested_types_by_name['ParametersEntry']
_TRAININGRESPONSE = DESCRIPTOR.message_types_by_name['TrainingResponse']
_PREDICTIONREQUEST = DESCRIPTOR.message_types_by_name['PredictionRequest']
_PREDICTIONRESPONSE = DESCRIPTOR.message_types_by_name['PredictionResponse']
TrainingRequest = _reflection.GeneratedProtocolMessageType('TrainingRequest', (_message.Message,), {

  'ParametersEntry' : _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRAININGREQUEST_PARAMETERSENTRY,
    '__module__' : 'linear_classification_pb2'
    # @@protoc_insertion_point(class_scope:fast_ml_linear_regression.TrainingRequest.ParametersEntry)
    })
  ,
  'DESCRIPTOR' : _TRAININGREQUEST,
  '__module__' : 'linear_classification_pb2'
  # @@protoc_insertion_point(class_scope:fast_ml_linear_regression.TrainingRequest)
  })
_sym_db.RegisterMessage(TrainingRequest)
_sym_db.RegisterMessage(TrainingRequest.ParametersEntry)

TrainingResponse = _reflection.GeneratedProtocolMessageType('TrainingResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAININGRESPONSE,
  '__module__' : 'linear_classification_pb2'
  # @@protoc_insertion_point(class_scope:fast_ml_linear_regression.TrainingResponse)
  })
_sym_db.RegisterMessage(TrainingResponse)

PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONREQUEST,
  '__module__' : 'linear_classification_pb2'
  # @@protoc_insertion_point(class_scope:fast_ml_linear_regression.PredictionRequest)
  })
_sym_db.RegisterMessage(PredictionRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONRESPONSE,
  '__module__' : 'linear_classification_pb2'
  # @@protoc_insertion_point(class_scope:fast_ml_linear_regression.PredictionResponse)
  })
_sym_db.RegisterMessage(PredictionResponse)

_LINEARCLASSIFICATIONSERVICE = DESCRIPTOR.services_by_name['LinearClassificationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.fastmllinearclassificationB\037FastMLLinearClassificationProtoP\001Z\035fastmllinearclassificationspb\252\002\"Fast.ML.Linear.Classification.Grpc'
  _TRAININGREQUEST_PARAMETERSENTRY._options = None
  _TRAININGREQUEST_PARAMETERSENTRY._serialized_options = b'8\001'
  _TRAININGREQUEST._serialized_start=59
  _TRAININGREQUEST._serialized_end=244
  _TRAININGREQUEST_PARAMETERSENTRY._serialized_start=195
  _TRAININGREQUEST_PARAMETERSENTRY._serialized_end=244
  _TRAININGRESPONSE._serialized_start=246
  _TRAININGRESPONSE._serialized_end=287
  _PREDICTIONREQUEST._serialized_start=289
  _PREDICTIONREQUEST._serialized_end=345
  _PREDICTIONRESPONSE._serialized_start=347
  _PREDICTIONRESPONSE._serialized_end=384
  _LINEARCLASSIFICATIONSERVICE._serialized_start=387
  _LINEARCLASSIFICATIONSERVICE._serialized_end=618
# @@protoc_insertion_point(module_scope)
